[package]
name = "cargo_embargo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "3.2.15", features = ["derive"] }
glob = "0.3.0"
once_cell = "1.16.0"
regex = "1.7.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.89"
